"""empty message

Revision ID: 6f07decd1f44
Revises: f7978bf361cb
Create Date: 2018-11-26 16:37:39.266625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f07decd1f44'
down_revision = 'f7978bf361cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('object_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'users', ['object_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'object_user_id')
    # ### end Alembic commands ###
