"""empty message

Revision ID: f7978bf361cb
Revises: 35d0e15dd369
Create Date: 2018-11-25 21:00:01.351346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7978bf361cb'
down_revision = '35d0e15dd369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_reqs',
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('fid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fid'], ['users.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['users.id'], )
    )
    op.create_table('friends',
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('fid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fid'], ['users.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends')
    op.drop_table('friend_reqs')
    # ### end Alembic commands ###
